# https://dart.dev/tools/analysis

include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    always_declare_return_types: error
