name: somanyfeeds

packages:
  - apps/*
  - packages/*

scripts:
  format:
    run: dart format . --line-length 100 --set-exit-if-changed

  install:
    exec: dart pub get

  test:
    exec: flutter test

  cyclic_dependency_checks:
    run: dart run cyclic_dependency_checks -m .

  dev:
    exec: ACCESS_CONTROL_ALLOW_ORIGIN="*" dart_frog dev
    packageFilters:
      scope: damo_io_server
