name: damo_io_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  logger: ^2.0.2+1

dev_dependencies:
  cyclic_dependency_checks:
    git:
      url: https://github.com/dam5s/cyclic_dependency_checks.git
      ref: release/0.4.0
  dart_frog_cli: ^0.1.5
  lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
