name: damo_io_server
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async_support: { path: '../async_support' }
  dart_frog: ^1.0.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  networking_support: { path: '../networking_support' }
  prelude: { path: '../prelude' }
  rss_dart: ^1.0.4

dev_dependencies:
  cyclic_dependency_checks:
    git: { url: https://github.com/dam5s/cyclic_dependency_checks.git, ref: release/0.4.0 }
  dart_frog_cli: ^1.1.1
  lints: ^3.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
