name: async_support
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  cyclic_dependency_checks:
    git: { url: https://github.com/dam5s/cyclic_dependency_checks.git, ref: release/0.4.0 }
  lints: ^2.1.0
  test: ^1.24.0
