name: damo_io_server
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  async_support: 0.0.0
  dart_frog: ^1.0.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  networking_support: 0.0.0
  prelude: 0.0.0
  rss_dart: ^1.0.4
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.0
  test: ^1.24.0
