name: damo_io_server
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  async_support: 0.0.0
  html_support: 0.0.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  networking_support: 0.0.0
  prelude: 0.0.0
  rss_dart: ^1.0.4
  shelf_cors_headers: ^0.1.5
  http: ^1.2.0
  shelf: ^1.4.1
  shelf_hotreload: ^1.4.0
  shelf_static: ^1.1.2

dev_dependencies:
  lints: ^4.0.0
  mocktail: ^1.0.0
  test: ^1.25.0
