name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: 'Setup and tests'
        run: |
          make setup
          make check

      - name: 'Build container archive'
        run: | 
          make container
          docker save damo_io:latest | gzip > damo_io_container.tgz

      - name: 'Save app container'
        uses: actions/upload-artifact@v4
        with:
          name: damo_io_container
          path: damo_io_container.tgz
